# Generated by Django 3.2.14 on 2022-07-04 09:51

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('event_title', models.CharField(max_length=200, unique=True)),
                ('event_date', models.DurationField()),
                ('local', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=500)),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('slug', models.SlugField(unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0)),
                ('category', models.CharField(choices=[('Road Trip', 'Road Trip'), ('Track Day', 'Track Day'), ('Exposition', 'Exposition'), ('Trade Event', 'Trade Event'), ('Meeting Event', 'Meeting Event'), ('Other Events', 'Other Events')], default='Other Events', max_length=15)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
