# Generated by Django 3.2.14 on 2022-07-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20220707_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='featured_image',
            new_name='event_image',
        ),
    ]
