# Generated by Django 3.2.14 on 2022-07-25 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_commentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='presence_go',
            field=models.ManyToManyField(blank=True, related_name='presence_go', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='presence_maybe',
            field=models.ManyToManyField(blank=True, related_name='presence_maybe', to=settings.AUTH_USER_MODEL),
        ),
    ]
