# Generated by Django 3.2.14 on 2022-07-19 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0003_car_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='featured_image',
            new_name='car_image',
        ),
    ]
