# Generated by Django 3.2.14 on 2022-07-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_ratecar'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratecar',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
