# Generated by Django 3.2.14 on 2022-07-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0009_ratecar_rated_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratecar',
            name='rated_user',
        ),
    ]
