# Generated by Django 3.2.14 on 2022-08-09 08:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0010_remove_ratecar_rated_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
